services:
  pocketbase:
    hostname: pocketbase-server
    build:
      context: ./pocketbase_app
    env_file: ".env"
    ports:
      - 8090:8090
    volumes:
      - ./pb_data:/app/pocketbase/pb_data

  telegram_bot:
    build: ./telegram_bot
    env_file: ".env"
    depends_on:
      - pocketbase
